import {focusMarkup,reviewRequest} from '../src/task-focus.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import ts from 'typescript';
import {JSDOM} from 'jsdom';
const source=(await readFile(new URL('../src/browser-workspace.ts',import.meta.url),'utf8')).replace(/^import .*;\s*$/gm,'').replace('export function','function');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
test('modal opening hides native browser without relying on animation frames',async()=>{
 const dom=new JSDOM('<div id="app"><aside></aside><main><header></header><nav></nav></main></div>',{url:'https://localoud.fixture'});const calls=[];
 Object.defineProperty(dom.window,'innerWidth',{value:1280,writable:true});
 const context={focusMarkup,reviewRequest,window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,MutationObserver:dom.window.MutationObserver,ResizeObserver:class{observe(){}},isTauri:()=>true};
 const setup=vm.runInNewContext(js+';setupBrowserWorkspace',context);const ui=setup(async(command,args)=>{calls.push({command,args});});
 await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,true);
 const dialog=dom.window.document.createElement('dialog');dom.window.document.querySelector('#app').append(dialog);dialog.setAttribute('open','');
 await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,false);
 dialog.removeAttribute('open');await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,true);
 dom.window.innerWidth=900;ui.showWorkspace();await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,false);
 ui.showBrowser();await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,true);
 ui.setWorkflow('<p>ファイルを修正</p><button data-flow-action="review">レビュー</button>',()=>{});
 assert.match(dom.window.document.querySelector('#workflow-bar').textContent,/ファイルを修正/);
 dom.window.document.querySelector('#browser-toggle').click();await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,false);
 assert.equal(dom.window.document.querySelector('#workflow-bar').hidden,false);assert.equal(dom.window.document.querySelector('#app').classList.contains('chatgpt-hidden'),true);assert.equal(dom.window.localStorage.getItem('localoud-browser-hidden'),'true');
 dom.window.document.querySelector('#browser-toggle').click();await new Promise(r=>setImmediate(r));assert.equal(calls.at(-1).args.bounds.visible,true);
 const sidebar=dom.window.document.querySelector('#sidebar-divider');sidebar.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(dom.window.localStorage.getItem('localoud-sidebar-width'),'250');
 assert.equal(dom.window.document.querySelector('#workflow-shell').parentElement.tagName,'MAIN');
 assert.ok(calls.every(c=>c.command==='browser_layout'));
 dom.window.close();
});
