import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../../../extensions/chatgpt/content.js',import.meta.url),'utf8');
async function fixture(overrides={}){let receive,insertions=0,sends=0;const results=[];const dom={composer:()=>({textContent:''}),conversationId:()=>null,generating:()=>false,hasComposerAttachments:()=>false,selectModelSettings:async()=>true,insertPrompt:()=>{insertions++;return true;},send:async()=>{sends++;return true;},...overrides};const context=vm.createContext({CLF_DOM:dom,setTimeout:()=>0,Date,console,chrome:{runtime:{id:'fixture',onMessage:{addListener:fn=>receive=fn},sendMessage:async m=>{if(m.kind==='result')results.push(m.payload);return m.kind==='binding'?null:{};}}}});vm.runInContext(source,context);return {run:async command=>{receive(command,{id:'fixture'},()=>{});for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve));},results,counts:()=>({insertions,sends})};}
test('browser transport refuses another conversation before inserting or sending',async()=>{const f=await fixture({conversationId:()=> 'different'});await f.run({kind:'send',id:'op',session:'s',conversation:'expected',model:'astra',text:'test'});assert.deepEqual(f.counts(),{insertions:0,sends:0});assert.match(f.results[0].error,/別の会話/);});
test('an unconfirmed model never sends and ambiguous sends are not retried',async()=>{const denied=await fixture({selectModelSettings:async()=>false});await denied.run({kind:'send',id:'op',session:'s',conversation:null,model:'astra',text:'test'});assert.deepEqual(denied.counts(),{insertions:0,sends:0});const ambiguous=await fixture({send:async()=>false});await ambiguous.run({kind:'send',id:'op',session:'s',conversation:null,model:'astra',text:'test'});assert.match(ambiguous.results[0].error,/自動再送はしません/);assert.equal(ambiguous.counts().insertions,1);});
test('existing user drafts are never overwritten',async()=>{const f=await fixture({composer:()=>({textContent:'user draft'})});await f.run({kind:'send',id:'op',session:'s',conversation:null,model:'astra',text:'test'});assert.deepEqual(f.counts(),{insertions:0,sends:0});assert.match(f.results[0].error,/下書き/);});
