PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY, name TEXT NOT NULL, root TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), plan_id TEXT REFERENCES plans(id), status TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_dependencies(task_id TEXT NOT NULL REFERENCES tasks(id), dependency_id TEXT NOT NULL REFERENCES tasks(id), PRIMARY KEY(task_id,dependency_id), CHECK(task_id != dependency_id));
CREATE TABLE IF NOT EXISTS workers(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS provider_threads(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), task_id TEXT REFERENCES tasks(id), provider TEXT NOT NULL, provider_thread_id TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(provider,provider_thread_id));
CREATE TABLE IF NOT EXISTS turns(id TEXT PRIMARY KEY, thread_id TEXT NOT NULL REFERENCES provider_threads(id), provider_turn_id TEXT, status TEXT NOT NULL, intent TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS context_capsules(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS context_capsule_items(id TEXT PRIMARY KEY, capsule_id TEXT NOT NULL REFERENCES context_capsules(id), source TEXT NOT NULL, reference TEXT NOT NULL, token_estimate INTEGER NOT NULL CHECK(token_estimate >= 0));
CREATE TABLE IF NOT EXISTS context_retrievals(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), worker_id TEXT REFERENCES workers(id), source TEXT NOT NULL, query TEXT NOT NULL, token_budget INTEGER NOT NULL, token_estimate INTEGER NOT NULL, result_ref TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS decisions(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), statement TEXT NOT NULL, reason TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT, thread_id TEXT REFERENCES provider_threads(id), kind TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS worktrees(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), path TEXT NOT NULL UNIQUE, base_sha TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), verdict TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS model_usage(id TEXT PRIMARY KEY, provider TEXT NOT NULL, model TEXT NOT NULL, task_id TEXT REFERENCES tasks(id), turn_id TEXT, prompt_tokens INTEGER, cached_tokens INTEGER, completion_tokens INTEGER, estimated_cost REAL, latency_ms INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS events_thread ON events(thread_id,id);
PRAGMA user_version = 1;
